version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=domain.com, www.domain.com
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
