version: '3.9'
services:
  database:
    hostname: database
    container_name: database
    image: mongo
    ports:
      - '27017:27017'
    tty: true
    command: mongod --quiet --logpath /dev/null

  app:
    container_name: discord_dev
    depends_on: [database]
    image: discord_dev
    build:
      context: .
      dockerfile: .docker/development/Dockerfile
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://database:27017
      - JWT_SECRET_KEY=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    tty: true