FROM node:16-alpine AS builder

RUN mkdir -p /app
WORKDIR /app

COPY ./frontend ./frontend
COPY ./types ./types
COPY ./nginx ./nginx

RUN cd /app/frontend && yarn install

RUN cd /app/frontend && yarn build:web

FROM nginx:1.16.0-alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
