FROM node:16-alpine

RUN mkdir -p /app
WORKDIR /app

COPY ./backend ./backend
COPY ./types ./types

EXPOSE 4000
EXPOSE 4001

WORKDIR /app/backend
RUN yarn install
RUN yarn build

CMD cd /app/backend && yarn start:prod
