export const ApiResponses = {
  UNAUTHORIZED: 'Unauthorized',
  SOMETHING_WRONG: 'Something wrong',
  EMAIL_ALREADY_USED: 'Email already in use',
  INVALID_CREDENTIALS: 'Email or password is invalid',
  TOKEN_EXPIRED: 'Your token has expired! Please log in again',
  INVALID_TOKEN: 'Invalid Token. Please log in again!',
  USER_NOT_FOUND: 'User not found',
  NO_ROOMS_FOUND: 'No rooms found',
  NO_MESSAGES_FOUND: 'No messages found',
  REQUEST_NOT_FOUND: 'Request not found!',
  ERROR_CREATE_REQUEST: `Hm, didn't work. Double check that the capitalization, spelling, any spaces, and numbers are correct.`,
  ALREADY_FRIENDS: `You're already friends with that user!`,
  REQUEST_ALREADY_EXISTS: 'Friend request already exists!',
  ROOM_NOT_FOUND: 'Room not found',
  NO_FRIENDS: 'This user has no friends',
  QS_EXTRA_INFO_REQUIRED: 'The query param extraInfo is required',
};
