name: ci

on:
  push:
    branches:
      - "master"
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: cd backend && yarn
      - name: Run unit tests
        run: cd backend && yarn test

  build-backend-image:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./backend/.docker/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_REPO_BACKEND }}:${{ github.sha }}

  build-frontend-image:
    runs-on: ubuntu-latest
    needs: [test-backend]
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./frontend/.docker/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_REPO_FRONTEND }}:${{ github.sha }}
          build-args: |
            "API_ROOT=${{ secrets.API_ROOT }}"
            "WS_ROOT=${{ secrets.WS_ROOT }}"
            "API_VERSION=1" 

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [build-backend-image]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd /root/discord-backend && ./deploy.sh ${{ github.sha }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [build-frontend-image]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: cd /root/discord-frontend && ./deploy.sh ${{ github.sha }}
